FROM python:3.9

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# copy every content from the local file to the image
COPY . .

CMD ["python", "worker.py"]
